import { Profile } from './store';
import { ReceiptItem } from './receiptEmbed';
import { money, longDateYear } from './format';

// Printable invoice. Line items are computed by the invoice screen from raw
// entries so days group by type and rate. Deductions never appear here.

export type InvoiceLine = { desc: string; amount: number };

const esc = (s: string) =>
  s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

export function buildInvoiceHtml(opts: {
  invoiceNo: string;
  client: string;
  project?: string;
  profile: Profile;
  billDate: string;   // ISO
  dueDate: string;    // ISO
  lines: InvoiceLine[];
  receipts: ReceiptItem[];
}): string {
  const { invoiceNo, client, project, profile, billDate, dueDate, lines, receipts } = opts;
  const total = lines.reduce((s, l) => s + l.amount, 0);
  const fromName = (profile.businessName || profile.name || 'Contractor').trim();
  const fromDetails = [profile.businessAddress, profile.businessPhone, profile.businessEmail]
    .map((x) => (x || '').trim())
    .filter(Boolean)
    .map((x) => esc(x).replace(/\n/g, '<br/>'))
    .join('<br/>');

  const lineRows = lines
    .map((l) => `<tr><td>${esc(l.desc)}</td><td class="amt">${money(l.amount)}</td></tr>`)
    .join('');

  const receiptBlock = receipts.length
    ? `<div class="receipts"><h3>Receipts (${receipts.length})</h3><div class="grid">${receipts
        .map((x) => `<figure><img src="${x.dataUri}" /><figcaption>${esc(x.label)}</figcaption></figure>`)
        .join('')}</div></div>`
    : '';

  return `<!DOCTYPE html>
<html><head><meta charset="utf-8" />
<style>
  * { box-sizing: border-box; }
  body { font-family: -apple-system, Helvetica, Arial, sans-serif; color: #1F1F1D; margin: 0; padding: 44px; font-size: 13px; line-height: 1.5; }
  .top { display: flex; justify-content: space-between; align-items: flex-start; }
  h1 { font-size: 24px; margin: 0; letter-spacing: 0.06em; }
  .meta { text-align: right; color: #5F5E5A; font-size: 12px; }
  .meta b { color: #1F1F1D; font-size: 14px; }
  .parties { display: flex; gap: 40px; margin: 26px 0 8px; }
  .party h3 { font-size: 10px; text-transform: uppercase; letter-spacing: 0.06em; color: #9a9a93; margin: 0 0 4px; }
  .party div { font-size: 14px; font-weight: 600; }
  .party .det { font-size: 11px; color: #5F5E5A; margin: 4px 0 0; font-weight: 400; line-height: 1.5; }
  .pay { margin-top: 22px; font-size: 12px; }
  .pay h3 { font-size: 10px; text-transform: uppercase; letter-spacing: 0.06em; color: #9a9a93; margin: 0 0 4px; }
  table { width: 100%; border-collapse: collapse; margin-top: 18px; }
  td { padding: 9px 0; border-bottom: 1px solid #ECECEC; }
  td.amt { text-align: right; white-space: nowrap; }
  tr.total td { border-bottom: none; border-top: 2px solid #1F1F1D; font-weight: 700; font-size: 15px; padding-top: 12px; }
  .terms { margin-top: 22px; color: #5F5E5A; font-size: 11px; }
  .receipts { margin-top: 30px; page-break-before: always; }
  .receipts h3 { font-size: 11px; text-transform: uppercase; letter-spacing: 0.06em; color: #5F5E5A; }
  .grid { display: flex; flex-wrap: wrap; gap: 12px; }
  figure { margin: 0; width: 46%; page-break-inside: avoid; }
  figure img { width: 100%; border: 1px solid #e4e4df; border-radius: 4px; }
  figcaption { font-size: 10px; color: #6b6b66; margin-top: 3px; }
</style></head>
<body>
  <div class="top">
    <h1>INVOICE</h1>
    <div class="meta">
      <b>${esc(invoiceNo)}</b><br/>
      Issued ${longDateYear(billDate)}<br/>
      Due ${longDateYear(dueDate)}
    </div>
  </div>

  <div class="parties">
    <div class="party"><h3>From</h3><div>${esc(fromName)}</div>${fromDetails ? `<p class="det">${fromDetails}</p>` : ''}</div>
    <div class="party"><h3>Bill to</h3><div>${esc(client || 'Unassigned')}</div>${project ? `<p class="det">Project: ${esc(project)}</p>` : ''}</div>
  </div>

  <table>
    <tbody>
      ${lineRows}
      <tr class="total"><td>Total due</td><td class="amt">${money(total)}</td></tr>
    </tbody>
  </table>

  ${profile.paymentInstructions?.trim() ? `<div class="pay"><h3>Payment</h3>${esc(profile.paymentInstructions.trim()).replace(/\n/g, '<br/>')}</div>` : ''}
  <div class="terms">Payment terms: net ${profile.paymentTermsDays || 0} days. Generated by HitchWell.</div>
  ${receiptBlock}
</body></html>`;
}
