// Regenerates lib/perdiemData.ts from GSA's Per Diem Master Rates File.
//
// Usage:
//   npm i -D xlsx
//   node scripts/import-perdiem.mjs ~/Downloads/FY2026_PerDiemMasterRatesFile.xlsx
//
// Download the master file from:
//   https://www.gsa.gov/travel/plan-book/per-diem-rates/per-diem-files
// Re-run each August when GSA publishes the new fiscal year.
//
// The file has one row per area and season (lodging varies by month, M&IE does
// not), so we keep one M&IE record per area. Lodging is tracked as an actual
// expense in the app and is not imported.

import * as XLSX from 'xlsx';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const input = process.argv[2];
if (!input) {
  console.error('Usage: node scripts/import-perdiem.mjs <path-to-gsa-master.xlsx>');
  process.exit(1);
}

const wb = XLSX.readFile(input);
const ws = wb.Sheets[wb.SheetNames[0]];
const rows = XLSX.utils.sheet_to_json(ws, { header: 1, blankrows: false });

// Find the header row (the one containing STATE and a meals column).
let headerIdx = rows.findIndex(
  (r) => r.some((c) => String(c).trim().toUpperCase() === 'STATE') && r.some((c) => /M&IE|MEALS/i.test(String(c)))
);
if (headerIdx < 0) {
  console.error('Could not find a header row with STATE and an M&IE column. Headers seen:');
  console.error(rows.slice(0, 5));
  process.exit(1);
}
const header = rows[headerIdx].map((c) => String(c).trim());
const col = (re) => header.findIndex((h) => re.test(h));
const ci = {
  state: col(/^state$/i),
  dest: col(/destination/i),
  county: col(/county|location defined/i),
  mie: col(/m&ie|meals/i),
};
if (ci.state < 0 || ci.dest < 0 || ci.mie < 0) {
  console.error('Missing required columns. Detected:', ci, '\nHeaders:', header);
  process.exit(1);
}

// Detect fiscal year from the M&IE header (e.g. "FY26 M&IE") or the title row.
const fyText = (header[ci.mie] || '') + ' ' + String(rows[0]?.join(' ') || '');
const fyMatch = fyText.match(/FY\s?(20)?(\d{2})/i) || fyText.match(/(20\d{2})/);
let fy = 0;
if (fyMatch) {
  const raw = fyMatch[fyMatch.length - 1];
  fy = raw.length === 2 ? 2000 + Number(raw) : Number(raw);
}

const seen = new Map();
const order = [];
for (const r of rows.slice(headerIdx + 1)) {
  const state = String(r[ci.state] ?? '').trim();
  const dest = String(r[ci.dest] ?? '').trim();
  const county = ci.county >= 0 ? String(r[ci.county] ?? '').trim() : '';
  const mieRaw = r[ci.mie];
  if (!state || state.length !== 2 || !dest) continue;
  if (/standard conus/i.test(dest)) continue;
  const mie = Number(String(mieRaw).replace(/[^0-9.]/g, ''));
  if (!mie) continue;
  const key = `${state}|${dest}|${county}`;
  if (seen.has(key)) continue;
  seen.set(key, { state, dest, county, mie });
  order.push(key);
}

const esc = (s) => s.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
const lines = [
  "import type { NsaArea } from './perdiem';",
  '',
  `// AUTO-GENERATED by scripts/import-perdiem.mjs from GSA's per diem master file.`,
  `// One M&IE record per area. Do not edit by hand; re-run the import to refresh.`,
  '',
  `export const NSA_DATA_FY = ${fy || 0};`,
  'export const NSA_RATES_DATA: NsaArea[] = [',
];
for (const key of order) {
  const { state, dest, county, mie } = seen.get(key);
  const c = county ? `, county: '${esc(county)}'` : '';
  lines.push(`  { state: '${esc(state)}', city: '${esc(dest)}'${c}, mie: ${mie} },`);
}
lines.push('];', '');

const out = resolve(__dirname, '..', 'lib', 'perdiemData.ts');
writeFileSync(out, lines.join('\n'));
console.log(`Wrote ${order.length} areas (FY${fy || '?'}) to ${out}`);
